[workspace]
channels = ["https://prefix.dev/wv-forge", "https://prefix.dev/conda-forge"]
platforms = ["linux-64"]
preview = ["pixi-build"]

[system-requirements]
cuda = "12.9"

[dependencies]
sam3d-objects = { path = "recipe" }
pytorch3d = "*"
utils3d = "*"
pipeline = "*"
moge = "*"
python = ">=3.12"
cuda-version = ">=12.6.0"
pytorch-gpu = ">=2.6.0"

[pypi-dependencies]
spconv-cu121 = ">=2.3"

[package]
name = "sam3d-objects"
version = "0.0.1"

[package.build]
backend = { name = "pixi-build-rattler-build", version = "0.3.*" }
