[workspace]
name = "open3d"
channels = ["conda-forge", "nvidia"]
platforms = ["linux-64"]
preview = ["pixi-build"]

[system-requirements]
cuda = "12.6"

[dependencies]
open3d = { path = "." }

[package]
name = "open3d"
version = "0.19.0"

[package.build]
backend = { name = "pixi-build-rattler-build", version = "*", channels = ["https://prefix.dev/pixi-build-backends", "conda-forge", "nvidia"] }

[package.build.source]
path = "recipe"
