[workspace]
name = "pccm"
channels = ["conda-forge"]
platforms = ["linux-64"]
preview = ["pixi-build"]

[dependencies]
pccm = { path = "." }

[package]
name = "pccm"
version = "0.4.16"

[package.build]
backend = { name = "pixi-build-rattler-build", version = "*", channels = ["https://prefix.dev/pixi-build-backends", "conda-forge"] }

[package.build.source]
path = "recipe"
