[workspace]
name = "cumm"
channels = [
  "file:///home/lllang/Documents/ykkap_xtech-Notebook/01_Projects/YKK-Point-Cloud/ext_pkgs/pccm/.pixi/build/work/pccm-g0iKkfNOTTk-TwLmj22Yeao/output",
  "conda-forge",
  "nvidia"
]
platforms = ["linux-64"]
preview = ["pixi-build"]

[dependencies]
cumm = { path = "." }

[package]
name = "cumm"
version = "0.7.11"

[package.build]
backend = { name = "pixi-build-rattler-build", version = "*", channels = ["https://prefix.dev/pixi-build-backends", "conda-forge", "nvidia"] }

[package.build.source]
path = "recipe"
